#!/usr/bin/env bash

cd $HOME;
rm -dr $HOME/ucr
git clone https://github.com/just4kick/ucr.git
cd $HOME/ucr;

touch $HOME/.local/bin/ucr 
ln -s $HOME/ucr/ucr $HOME/.local/bin/ucr
ln -s $HOME/ucr/ucrupdate $HOME/.local/bin


